name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*' # Trigger only when pushing tags that start with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || '' }}

    - name: Build binary
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zcash-paperwallet${{ matrix.os == 'windows-latest' && '.exe' || matrix.os == 'macos-latest' && '.dmg' || '' }}
        path: target/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v2

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:        
        files: zcash-paperwallet${{ matrix.os == 'windows-latest' && '.exe' || matrix.os == 'macos-latest' && '.dmg' || '' }}