name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || '' }}

    - name: Build binary
      run: |
        cargo clean
        cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: zcash-paperwallet
        path: cli/target/release/zcash-paperwallet${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Release ${{ github.event.release.tag_name }}
        draft: false
        prerelease: false
        files: |
          zcash-paperwallet
